#!/bin/bash
while [ ! -f /opt/instruqt/bootstrap/host-bootstrap-completed ]
do
    echo "Waiting for Instruqt to finish booting the VM"
    sleep 1
done

# This has to be run after installation. 
systemctl enable --now cockpit.socket
firewall-cmd --add-service=cockpit --permanent
firewall-cmd --reload

subscription-manager config --rhsm.manage_repos=1
subscription-manager register --activationkey=${ACTIVATION_KEY} --org=12451665 --force

dnf -y install bind-utils
dnf -y install ipa-client

export IDM_SERVER_NAME=idmserver.idmworkshop.lab
export IDM_REPLICA_NAME=idmreplica.idmworkshop.lab
export IDM_CLIENT_NAME=idmclient.idmworkshop.lab

echo "Adding wheel" > /root/post-run.log
usermod -aG wheel rhel

echo "setting password" >> /root/post-run.log
echo redhat | passwd --stdin rhel

echo "DONE" >> /root/post-run.log

# Add an entry to the /etc/hosts file for the satellite server if it doesn't already exist.
tee -a /root/labsetup.sh << EOF
#!/bin/bash
IDM=\$(nslookup idmserver | awk '/^Address: / { print \$2 }')
nmcli conn mod 'Wired connection 1' ipv4.dns \$IDM
nmcli conn up 'Wired connection 1'
hostnamectl set-hostname $IDM_CLIENT_NAME
EOF

chmod +x /root/labsetup.sh

mv /etc/yum.repos.d/google-cloud.repo /root
timedatectl set-timezone America/New_York

